import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import NotificationProvider from "./_contexts/NotificationContext";
import { Toaster } from "@/components/ui/toaster";

//const inter = Inter({ subsets: ["latin"] });

const nunitoFont = Nunito({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="">
        <NotificationProvider>{children}</NotificationProvider>
        <Toaster />
      </body>
    </html>
  );
}
